name: ocr
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
  - nvidia
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - addict=2.4.0=pyhcf101f3_4
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py312h6b91d65_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-doc=0.0.4=pyhcf101f3_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - backports.zstd=1.3.0=py312h06d0912_0
  - blas=1.0=mkl
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py312hf90b1b7_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - cuda-cccl=12.9.27=0
  - cuda-cccl_win-64=12.9.27=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhcf101f3_2
  - datasets=4.4.2=pyhcf101f3_0
  - dill=0.4.0=pyhcf101f3_1
  - dnspython=2.8.0=pyhcf101f3_0
  - double-conversion=3.3.1=he0c23c2_0
  - easydict=1.13=pyhff2d567_1
  - einops=0.8.1=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_4
  - fastapi=0.128.0=h0ea4129_1
  - fastapi-cli=0.0.20=pyhcf101f3_0
  - fastapi-core=0.128.0=pyhcf101f3_1
  - filelock=3.20.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py312h05f76fc_0
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.0.0=h9e37d49_0
  - hf-xet=1.2.1=py310hfb9af98_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py312he06e257_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2025.3.0=h57928b3_642
  - jinja2=3.1.6=pyhcf101f3_1
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.9=py312h78d62e6_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h5f2f476_6_cuda
  - libarrow-acero=22.0.0=h7d8d6a5_6_cuda
  - libarrow-compute=22.0.0=h2db994a_6_cuda
  - libarrow-dataset=22.0.0=h7d8d6a5_6_cuda
  - libarrow-substrait=22.0.0=hf865cc0_6_cuda
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.9.0=13_hc41557d_netlib
  - libclang13=21.1.7=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcurl=8.17.0=h43ecb02_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.0=h7025463_0
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=13_h018ca30_netlib
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.9.82=0
  - libnvfatbin-dev=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libparquet=22.0.0=h7051d1f_6_cuda
  - libpng=1.6.53=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=hfc51747_1
  - libutf8proc=2.11.2=hb980946_0
  - libuv=1.51.0=hfd05255_1
  - libwebp=1.6.0=h4d5522a_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.10.0=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h0ebf65c_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.1.0=h6a75c08_48682
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msys2-conda-epoch=20160418=1
  - multidict=6.7.0=py312h05f76fc_0
  - multiprocess=0.70.18=py312he5662c2_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.0=py312ha72d056_0
  - opencl-headers=2025.06.13=he0c23c2_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hc128f0a_2
  - pcre2=10.44=h99c9b8b_2
  - pillow=10.4.0=py312h381445a_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - propcache=0.3.1=py312h31fea79_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pyarrow=22.0.0=py312h2e8e312_0
  - pyarrow-core=22.0.0=py312h6654431_0_cuda
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py312hdabe01f_1
  - pydantic-extra-types=2.11.0=pyhd8ed1ab_0
  - pydantic-settings=2.12.0=pyh3cfb1c2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.9.0=py312h520aab8_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-multipart=0.0.21=pyh332efcf_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py312h99c85cd_1
  - python_abi=3.12=3_cp312
  - pytorch=2.5.0=py3.12_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h05f76fc_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - re2=2025.11.05=ha104f34_0
  - regex=2025.11.3=py312he06e257_1
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.17.1=pyhcf101f3_0
  - safetensors=0.7.0=py312hb0142fd_0
  - setuptools=80.9.0=py312haa95532_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.1=hda9a48d_0
  - starlette=0.50.0=pyhfdc7a7d_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2021.13.0=hd094cb3_4
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.4=py312h362b069_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.4=py312he06e257_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.47.1=pyhd8ed1ab_0
  - typer=0.21.0=pyhbb89825_0
  - typer-slim=0.21.0=pyhcf101f3_0
  - typer-slim-standard=0.21.0=hd63da06_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py312he06e257_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - uvicorn=0.40.0=pyh6dadd2b_0
  - uvicorn-standard=0.40.0=hcfb189c_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - watchfiles=1.1.1=py312hb0142fd_0
  - websockets=15.0.1=py312he5662c2_2
  - wheel=0.45.1=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xxhash=0.8.3=hbba6f48_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py312h05f76fc_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - torchaudio==2.5.0
      - torchvision==0.20.0
